### PR TITLE
Universal destroy_ocp

### PR DESCRIPTION
**Pull request by abays**
CI improvement that allows `make destroy_ocp` to agnostically clean whatever previous OCP cluster might exist (regardless of whether IPI or AI)

### CODE REVIEW

**Comment by dprince** [comment]
universal destruction! whats not to like here...

One question though. Doesn't this put us at risk of breakage if for example dev-scripts cleanup is broken again (it was just recently broken for example).

**Comment by abays** [comment]
> universal destruction! whats not to like here...
> 
> One question though. Doesn't this put us at risk of breakage if for example dev-scripts cleanup is broken again (it was just recently broken for example).

That's actually a good point.  Perhaps we should add an `ignore_errors: true` to the `import_playbook` for `'ocp_dev_scripts_destroy.yaml`.  Thoughts?

**Comment by mpryc** [comment]
> > universal destruction! whats not to like here...
> > One question though. Doesn't this put us at risk of breakage if for example dev-scripts cleanup is broken again (it was just recently broken for example).
> 
> That's actually a good point. Perhaps we should add an `ignore_errors: true` to the `import_playbook` for `'ocp_dev_scripts_destroy.yaml`. Thoughts?

From my perspective if something is broken I would prefer it to fail rather then silently hide problem. If we ignore broken cleanup this probably will affect next job in the CI queue and the job will fail anyway resulting us to spend more time on finding why the job fail then having direct information that environment was not properly cleaned up before starting new job.

**Comment by abays** [comment]
> > > universal destruction! whats not to like here...
> > > One question though. Doesn't this put us at risk of breakage if for example dev-scripts cleanup is broken again (it was just recently broken for example).
> > 
> > 
> > That's actually a good point. Perhaps we should add an `ignore_errors: true` to the `import_playbook` for `'ocp_dev_scripts_destroy.yaml`. Thoughts?
> 
> From my perspective if something is broken I would prefer it to fail rather then silently hide problem. If we ignore broken cleanup this probably will affect next job in the CI queue and the job will fail anyway resulting us to spend more time on finding why the job fail then having direct information that environment was not properly cleaned up before starting new job.

Okay, let's keep it as it is for now

**Pull request merged**
