### PR TITLE
wait stable increase & freeip_con centos9 stream

### PR DESCRIPTION
**Pull request by pinikomarov**
increase wait time for cluster stability

### CODE REVIEW

**Comment by pinikomarov** [comment]
@abays this passes the failed task , so the patch works : 
`TASK [Wait until the OpenShift cluster is stable] ******************************
`
`^[[0;33mAll clusteroperators are stable^[[0m
`
it fails on a different issue though: 
`ESC[0;31mTrying to pull quay.io/freeipa/freeipa-server:centos-8-stream...ESC[0m
ESC[0;31mError: initializing source docker://quay.io/freeipa/freeipa-server:centos-8-stream: reading manifest centos-8-stream in quay.io/freeipa/freeipa-server: manifest unknown: manifest unknownESC[0m
`

**Comment by pinikomarov** [comment]
updated freeipa to cen9 stream

**Comment by pinikomarov** [comment]
recheck

**Comment by pinikomarov** [comment]
check rebuild here : https://rhos-ci-jenkins.lab.eng.tlv2.redhat.com/view/DFG/view/ospk8s/view/ospdo_ci/job/DFG-ospk8s-osp-director-dev-tools-ai-pr/735

**Comment by pinikomarov** [comment]
@abays this is passing can we proceed to merge ?

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
