### PR TITLE
[v1.2.x-backports] backport to get latest master branch in sync

### PR DESCRIPTION
**Pull request by stuggi**
backport of patches, except osdeploy related ones (e.g. 38b6b2f65eae4625744d4056750fe7d15ee93f8c) to get branches in sync, especially using crucible and changes we did to ctlplane.

Also a v1.2.x specific patch to set csv_version to v1.2.x-latest in var/default.yaml

### CODE REVIEW

**Comment by abays** [comment]
It looks like this one got cluttered a bit with old commits somehow

**Comment by stuggi** [comment]
> It looks like this one got cluttered a bit with old commits somehow

not sure I understand what you mean. This is a backport of the following commits to v1.2.x branch:

```
ade1381f37a4aab535d81ecb1b7ebc0d8832a91e    Change freeipa-server image tag to centos-8-stream
098c9c822f937b001fb2217fc3404041e4175aab    [OSPK8-447] Fix ipv6 routes and scenario config errors
bf6ac33aa31c4584d4a3490eef66344a631b4f02    add 16.2_ipv6_tlse_subnet.yaml config
af2d344389162075cee450e8ba759e57df7ea851    set correct networks definition for train_subnet scenario
b43bf19c501934f2bd140739bb87f6bd8ef5d455    Wait for osnetcfg to have configured interfaces + networks
27678751e3664fcc548429ae6f7e9643ae9342ca    bump container tags and reference tripleoclient tag from it
102d97be358f379a0f01912360cc4891cb93748a    Use Crucible for AI deployments (#304)
9ec10cf0e7f33f7978cdece06ac48c7f07e280ca    Support secrets repo for AI
9f280aa2b9bea3435e714e80ff7a170c47731deb    OSP17.0 ComputeHCI support
086c0aaa2bf96b4f09ce4e125354cbc7f5ca6cd7    [OSPK8-425] fix ansible-lint and remove unused playbook/role (#315)
ba19178d40a38f1c946a494a88b0247255d110db    A few README updates
d8a9fb02330c5132bc3e7fa5a9c1791db0d64967    Allow OCP version selection for Crucible AI (#317)
e6149e12c47aa955d707e901371395d520366623    Minor tweak to AI version selection (#321)
24fbd2b5a4c2dccc9181e605e38b2bed2d93362b    Remove Crucible bug fix hacks (#320)
16e891e5645a7585778f49e13aad753cbae03e3d    make sure cleanup task to run as root where needed
26e7915f0e24df2f8ca499251826fbe2667cf3e4    [OSPK8-451] Disable provisioning and OCP cluster network in nic config
2090bb469dfbac2eecf71122e04442ef5ec1de77    [OSPK8-451] Move ctlplane network to a default MTU
38740600aed6b399529c0e1d7f138f3b35745022    ansible-lint-action branch name change to main
7500a86ddbb347f364582f02421bed8db71d9265    fix ip net definitions and remaining 16.2 nic templates
dca879f742bbd6dc69be8eb805f8dcc5b4abc4d4    use OCP 4.8 as default base line
f3439543ed7946cb5937dd5223223631f8aeb127    Add forwarding DNS server on ctlplane network
3804838423a87bc9ee2fb5aa57da5bdb525ad9f6    remove /etc/dnsmasq.d/ctlplane.conf on openstack_cleanup
be49fa1f7befa60786d137e830126aff7049fb79    make sure all outgoing traffic gets masqueraded in both deploy methods
84057ba4cd848bb7e861051f3684be03e9ba0e96    [OSPK8-449] Automate compose/puddle information based on input file
72aa910d69ac20de541d164eaeb974550910b06e    Add vars to customize osp_release_auto_url
```

**Comment by abays** [comment]
Yep, my bad.

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
