### PR TITLE
[OSPK8-324 OSPK8-325] OSP17 remove DeployedNetworkEnvironment workaround

### PR DESCRIPTION
**Pull request by stuggi**
Depends-On: https://github.com/openstack-k8s-operators/osp-director-operator/pull/451

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
rebased

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
AI job 576 passed, merging it

**Pull request merged**
