### PR TITLE
Backport 420c4b6

### PR DESCRIPTION
**Pull request by pinikomarov**
Change default subscription pool to enable cnv repo

### CODE REVIEW

**Comment by pinikomarov** [comment]
+1

**Comment by pinikomarov** [comment]
@olliewalsh Not sure what's the holdup here , 
I requested a rerun for the failed staging job : 
https://rhos-ci-staging-jenkins.lab.eng.tlv2.redhat.com/blue/organizations/jenkins/osp-director-dev-tools-multibranch/detail/PR-390/2/pipeline

anything else needed here ?

**Comment by olliewalsh** [comment]
Would be best to create a new PR for the job name fix and land that first

**Pull request closed without merging**
