### PR TITLE
[v1.2.x-backports] AI support for baremetal deployments (#324)

### PR DESCRIPTION
**Pull request by abays**
(cherry-picked from commit 0a8d260c4b2d6bbd6f42c70db54ef6abdf6a8324)

(also cherry-picks efde1910c65ae36bc2b74ba78b71ad1fe48fea08)

### CODE REVIEW

**Review by pinikomarov — APPROVED** [review]
LGTM ,  no erroring out on ocp_destroy anymore:
[root@titan88 openstack-k8s]# gh pr status

Relevant pull requests in openstack-k8s-operators/osp-director-dev-tools

Current branch
  #355  [v1.2.x-backports] AI support for baremetal dep... [abays:1_2_x_324]


PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=18   changed=5    unreachable=0    failed=0    skipped=4    rescued=0    ignored=2

Sunday 22 May 2022  21:19:54 +0000 (0:00:00.298)       0:00:12.934 ************
===============================================================================
openstack cleanup --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.35s
[..]
Include AI variables ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.06s

`

**Comment by pinikomarov** [comment]
testing this PR in a full run here : 
http://tny.im/N63yN

**Comment by stuggi** [comment]
> testing this PR in a full run here : http://tny.im/N63yN

check https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/356

**Comment by stuggi** [comment]
> > testing this PR in a full run here : http://tny.im/N63yN
> 
> check #356

maybe we squash that one into this backport PR?

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
