### PR TITLE
use LIBGUESTFS_BACKEND=direct for virt-customize

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by abays** [comment]
I've had to use the same thing in the past with regards to `virt-customize`.  Just curious though, what is requiring us to need it here?

**Comment by stuggi** [comment]
> I've had to use the same thing in the past with regards to `virt-customize`. Just curious though, what is requiring us to need it here?

after the upgrade to rhel8.5 libvirt connection to libvirtd fail on the dev-scripts deployments for the ocp user when using virt-customize. since we can customize the qcow direct using the env var this can be prevented. not sure yet why we do not see this in 100% of the test runs.

**Comment by abays** [comment]
> > I've had to use the same thing in the past with regards to `virt-customize`. Just curious though, what is requiring us to need it here?
> 
> after the upgrade to rhel8.5 libvirt connection to libvirtd fail on the dev-scripts deployments for the ocp user when using virt-customize. since we can customize the qcow direct using the env var this can be prevented. not sure yet why we do not see this in 100% of the test runs.

Ack, understood

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
