### PR TITLE
add 3combo nodes option to the HA tamplate

### PR DESCRIPTION
**Pull request by pinikomarov**
This will setup osp controllers to run on ocp masters
This is to align with customer usage

How this will work : 
in the makefile OSP_RELEASE is loaded as an vars
file for any make target , and since its specified on the 
command line it will override the default.yaml values

This should allow running this setup in CI by specifying : 
DEVTOOLS_OSP_RELEASE: 16.2_fencing_subnet_3combo

### CODE REVIEW

**Comment by pinikomarov** [comment]
running a test run at : 
https://rhos-ci-staging-jenkins.lab.eng.tlv2.redhat.com/job/osp-director-dev-tools-ai-pr-custom-ha-fencing-pkomarov/7/

**Comment by pinikomarov** [comment]
patch works like it should, 
tested here : 
https://rhos-ci-staging-jenkins.lab.eng.tlv2.redhat.com/job/osp-director-dev-tools-ai-pr-custom-ha-fencing-pkomarov/7/

result: 
The 3 nodes are an OCP cluster, and each node is a master/worker
[ocp@titan88 ~]$ oc get nodes
NAME              STATUS   ROLES           AGE    VERSION
ostest-master-0   Ready    master,worker   3d1h   v1.20.11+c343126
ostest-master-1   Ready    master,worker   3d1h   v1.20.11+c343126
ostest-master-2   Ready    master,worker   3d1h   v1.20.11+c343126
[ocp@titan88 ~]$ oc get bmh -A
NAMESPACE               NAME                 PROVISIONING_STATUS   CONSUMER                ONLINE   ERROR
openshift-machine-api   openshift-worker-0   provisioned           computeleaf2            true     
openshift-machine-api   openshift-worker-1   provisioned           computeleaf1            true     
openshift-machine-api   ostest-master-0      unmanaged             ostest-fn8xc-master-0   true     
openshift-machine-api   ostest-master-1      unmanaged             ostest-fn8xc-master-1   true     
openshift-machine-api   ostest-master-2      unmanaged             ostest-fn8xc-master-2   true

**Comment by pinikomarov** [comment]
@abays can you take a look at this ? 
Thanks

**Review by stuggi — APPROVED** [review]
/lgtm

**Review by abays — APPROVED** [review]
/lgtm

**Comment by pinikomarov** [comment]
ok so we're good to merge ?

**Comment by pinikomarov** [comment]
@abays Thanks

**Pull request merged**
